import type { APIRoute } from "astro";

/**
 * Dynamic robots.txt — allows all crawlers but disallows legal (noindex) pages.
 * Points crawlers to the sitemap index generated by @astrojs/sitemap.
 */
export const GET: APIRoute = ({ site }) => {
  const sitemapUrl = site
    ? new URL("sitemap-index.xml", site).toString()
    : "https://muscar.ai/sitemap-index.xml";
  const body = [
    "User-agent: *",
    "Disallow: /impressum",
    "Disallow: /datenschutz",
    "Disallow: /de/impressum",
    "Disallow: /de/datenschutz",
    `Sitemap: ${sitemapUrl}`,
    "",
  ].join("\n");
  return new Response(body, { headers: { "Content-Type": "text/plain" } });
};
